### ISSUE TITLE
Regression Testing for AE Timelines v2.0.0

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/ae-timelines#25]
Confirm basic functionality and new features are working as expected in examples shown below:

Examples using v2.0.0 Release Candidate
[default](http://bl.ocks.org/samussiah/raw/0917733a1fda88b274bb482103c84e22/)
[custom](http://bl.ocks.org/samussiah/raw/56ed5bd11998cc8867876c8843db815e/)

**Basic Functionality (Tested every release)**
- [x] Check all spelling and grammar on the page
- [x] View colored plot points and their tooltips for adverse event information by hovering the mouse over the adverse event markers.
- [x] Confirm that the filters (Severity, Subject ID, System Organ Class, Related to Treatment) are working as expected: when selected, only relevant events should be visible along with the ratio and percentage of affected participants
- [x] Confirm that there is an option to sort the visible participants and it works as expected
- [x] Use a combination of sorting and filtering to ensure that more than one manipulation can be applied at once
- [x] Confirm detail view works as expected by clicking on a participant ID

**New Functionality (Tested in V2.0.0 only)**
- [x] (#20) Confirm that the date of an adverse event doesn't end in a circle
- [x] (#19) Confirm that a serious AE is notated by a different mark than a normal AE
- [x] (#26) Confirm that plot points marked as queried appear as a different color than other plot points and when clicked, display a message detailing the event and query

**Comment by brittsikora** [comment]
@jwildfire can you please review this?

**Comment by jwildfire** [comment]
@brittsikora Good start! 2nd bullet looks ok to me. 2 notes: 
- I'd combine items 3 through 6 in to a single check ("Make sure filters for X, Y and Z are behaving as expected")
- Add checks for the detail view accessible by clicking on a participant id.

**Comment by samussiah** [comment]
@brittsikora , these gists should cover regression testing:

[default](http://bl.ocks.org/samussiah/raw/0917733a1fda88b274bb482103c84e22/)
[custom](http://bl.ocks.org/samussiah/raw/56ed5bd11998cc8867876c8843db815e/)

**Comment by jwildfire** [comment]
@brittsikora we should add a test for #26, but other than that, this looks good.

**Comment by brittsikora** [comment]
Added a point for #26 - do you think that covers it?

**Comment by brittsikora** [comment]
passed testing - closing
